greetingMessage: This message is coming from Property File

hashMapValue: "{key1:'Value1',key2:'Value2'}"


#grettingMessage1:  Hello  ${greetingMessage}

greetingMessageList: List1,List2,List3
db.testMessage: This is Test Message 

management.endpoint:
 info.enabled: true
 web.exposure.include: "****"

